CREATE TABLE IF NOT EXISTS students (
  uid VARCHAR(64) PRIMARY KEY,
  name VARCHAR(128) NOT NULL,
  student_id VARCHAR(64) NOT NULL,
  course VARCHAR(128) NULL,
  school_year VARCHAR(32) NULL,
  section VARCHAR(32) NULL,
  phone VARCHAR(32) NULL,
  notes VARCHAR(255) NULL
);

CREATE TABLE IF NOT EXISTS faculty (
  uid VARCHAR(64) PRIMARY KEY,
  name VARCHAR(128) NOT NULL,
  faculty_id VARCHAR(64) NOT NULL,
  department VARCHAR(128) NULL,
  phone VARCHAR(32) NULL,
  notes VARCHAR(255) NULL
);

CREATE TABLE IF NOT EXISTS staff (
  uid VARCHAR(64) PRIMARY KEY,
  name VARCHAR(128) NOT NULL,
  staff_id VARCHAR(64) NOT NULL,
  department VARCHAR(128) NULL,
  phone VARCHAR(32) NULL,
  notes VARCHAR(255) NULL
);

CREATE TABLE IF NOT EXISTS visitors (
  uid VARCHAR(64) PRIMARY KEY,
  name VARCHAR(128) NOT NULL,
  purpose VARCHAR(128) NULL,
  valid_until DATE NULL,
  phone VARCHAR(32) NULL,
  notes VARCHAR(255) NULL
);

CREATE TABLE IF NOT EXISTS admins (
  uid VARCHAR(64) PRIMARY KEY,
  name VARCHAR(128) NOT NULL
);

CREATE TABLE IF NOT EXISTS scans (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  uid VARCHAR(64) NOT NULL,
  direction VARCHAR(8) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (id)
);
  CREATE TABLE IF NOT EXISTS admin_uid_rejections (
    id INT UNSIGNED NOT NULL AUTO_INCREMENT,
    posted_admin_uid VARCHAR(64) NOT NULL,
    scanned_uid VARCHAR(64) NULL,
    direction VARCHAR(8) NULL,
    reason VARCHAR(64) NULL,
    ip VARCHAR(64) NULL,
    user_agent VARCHAR(255) NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (id)
  );
